version: '3.3'
services:

  db:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/
    container_name: petstore-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_USER: petstore
      MYSQL_PASSWORD: "#petstore"
      MYSQL_DATABASE: petstore
    ports:
      - 3306:3306
    volumes:
      - ./docker-db:/var/lib/mysql
      #- ./docker/db-init:/docker-entrypoint-initdb.d
      #- ./docker/db-custom:/etc/mysql/conf.d
